apiVersion: v1
kind: Secret
metadata:
    name: cinder-csi-cloud-config
    namespace: kube-system
type: Opaque
stringData:
    cloud.conf: ENC[AES256_GCM,data:IHUjAAw67KA5htAF+b+/SvuHaT+rXLlhYwmMyABSLKrM10i2OSAnP/DLXaCJNwOsgOj45JORRPpI0sqGChK4SG28vg0kuoDlyY6tjoq0hZ4+9ZhPrIGCHoDLxvGeQI+Qz2lDHuQutwNbEtqy3P2MWiGMpqvJwcTjM+xlFE91UkRfP+3TYYf59tA1j2MmIaeMChPLYTgYreWJD6iB54AX+v04SLEHvxxPtlxjbie+QJcR4eVPp0CaPNc1Yil9YJrmdYB/SMnzPxP6aymA7g/4ns2pivq/Lc1im2+wVSESyQSNEqaeX41g7g+1jfo1jLFiLQOF4aEmDxKS44+Pvg6+lbmiOEngnlNkoPmv3DcQhfn08iNOlLTbzcVrCn7PKSy6LcpmVmxuXKVXSBY6Ooo48eXKTgT2t3Vs+uqitkXp5bM/JQdBTkkvfYMIUhDwNjpXmiJTCxtQUWn6xxP/Vj5qz20gmP3M0Cavqqa5AwDVNwo=,iv:iQ/2DIZmLLRQsCS1mEErjwGnbBC05Uid+Cf/yaK9x7M=,tag:O3K5xmYImErxODxh3RZetg==,type:str]
sops:
    age:
        - recipient: age1fjvdayhz0lzd3kwqjtnagwg0eveghl9x0a96hfcucudxvklcgq9qznt7xu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBONm5KUmkwL2VGallNSVdY
            UTFQdEdBdjhPZ1NBNUtvTTlERDdFN3BYcnp3CkxTaXJJYXZVeHYraGQ2U0NYaHBy
            TXZ5dE5GMmhuSzhDWmxGMzhOV3p5ZkkKLS0tIGlland5VnVuWVJWT2wxTURUcjJV
            UzB3NEEzV1JtYXlHM2dObHM4U2ptNDgKoPAcN2uteYrXP6JVhuyrV6z+iFqfIl7T
            ujPkyQ4jJdu6tok+2/XlDmeeiTXM8PR4gfwrvYnDcaU1o+yP/L5HDg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-06T12:50:24Z"
    mac: ENC[AES256_GCM,data:crHh/w6mMjVXDchFvVHv0mi+yoJHIchP3z1FqSIlU043RKz2pVkrqkFHstjZQgxLLnjtCo25Ek8WLenr+rhCcwUMjXsoJ6kShHD/YC0BSBOU6c1Jk6Sm3MWwwhMSo7UanMLTebDIaFY8cwgBPETmr/f37ScSFrMi6vW/LSA6NE0=,iv:hMirblNKcHNfbRnJll2x70CgEtCLQMdGt8JASM+uzJo=,tag:YeCJ2QKUIdkBe/U4ks5c9A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
