server:
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
    hosts: [ "argocd.protocoast.vm.fedcloud.eu" ]
    tls:
      - secretName: argocd-tls
        hosts:
          - argocd.protocoast.vm.fedcloud.eu
configs:
  params:
    server.insecure: true
