apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-cluster-issuer
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: platform
  source:
    repoURL: git@github.com:CMCC-Foundation/protocoast-infra.git
    targetRevision: main
    path: argocd/platform/cluster-issuer
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  revisionHistoryLimit: 5
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 5m
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - PruneLast=true
      - ServerSideApply=true
