apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-cinder-csi
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  project: platform
  sources:
    # Keep this pinned and bump by PR after staging validation.
    # For Kubernetes v1.34.x, use the 2.34.x cinder chart line.
    - repoURL: https://kubernetes.github.io/cloud-provider-openstack
      chart: openstack-cinder-csi
      targetRevision: 2.34.3
      helm:
        releaseName: cinder-csi
        valueFiles:
          - $values/helmfile/k8s-configs/cinder-csi/cinder-csi-values.yaml
    - repoURL: git@github.com:CMCC-Foundation/protocoast-infra.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  revisionHistoryLimit: 5
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 5m
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - PruneLast=true
      - ServerSideApply=true
