apiVersion: v1
kind: Secret
metadata:
  name: openstack-ca-cert
  namespace: kube-system
type: Opaque
stringData:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    REPLACE_WITH_OPENSTACK_CA_CERT
    -----END CERTIFICATE-----
