apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: data-jupyterhub-main
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - cluster: main
            server: https://kubernetes.default.svc
  template:
    metadata:
      name: 'data-jupyterhub-{{cluster}}'
      namespace: argocd
      finalizers:
        - resources-finalizer.argocd.argoproj.io
      annotations:
        argocd.argoproj.io/sync-wave: "40"
    spec:
      project: data
      sources:
        - repoURL: https://jupyterhub.github.io/helm-chart
          chart: jupyterhub
          targetRevision: 3.3.8
          helm:
            releaseName: jupyterhub
            valueFiles:
              - $values/helmfile/daskhub-helm/jhub-values.yaml
        - repoURL: https://github.com/Kosenuel/Test-Infra
          targetRevision: main
          ref: values
      destination:
        server: '{{server}}'
        namespace: daskhub
      revisionHistoryLimit: 5
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: 5
          backoff:
            duration: 10s
            factor: 2
            maxDuration: 5m
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
          - PruneLast=true
          - ServerSideApply=true
