apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: data-dask-gateway-main
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - cluster: main
            server: https://kubernetes.default.svc
  template:
    metadata:
      name: 'data-dask-gateway-{{cluster}}'
      namespace: argocd
      finalizers:
        - resources-finalizer.argocd.argoproj.io
      annotations:
        argocd.argoproj.io/sync-wave: "50"
    spec:
      project: data
      sources:
        - repoURL: https://helm.dask.org
          chart: dask-gateway
          targetRevision: 2022.6.1
          helm:
            releaseName: dask-gateway
            valueFiles:
              - $values/argocd/workloads/data/dask-gateway-values.yaml
        # - repoURL: https://github.com/CMCC-Foundation/protocoast-infra
        - repoURL: https://github.com/Kosenuel/Test-Infra
          targetRevision: main
          ref: values
      destination:
        server: '{{server}}'
        namespace: daskhub
      revisionHistoryLimit: 5
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: 5
          backoff:
            duration: 10s
            factor: 2
            maxDuration: 5m
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
          - PruneLast=true
          - SkipDryRunOnMissingResource=true
