apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: platform-cinder-csi-main
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - cluster: main
            server: https://kubernetes.default.svc
  template:
    metadata:
      name: 'platform-cinder-csi-{{cluster}}'
      namespace: argocd
      finalizers:
        - resources-finalizer.argocd.argoproj.io
      annotations:
        argocd.argoproj.io/sync-wave: "20"
    spec:
      project: platform
      ignoreDifferences:
        - group: apps
          kind: DaemonSet
          name: openstack-cinder-csi-nodeplugin
          namespace: kube-system
          managedFieldsManagers:
            - kube-controller-manager
            - kubelet
      sources:
        - repoURL: https://kubernetes.github.io/cloud-provider-openstack
          chart: openstack-cinder-csi
          targetRevision: 2.34.3
          helm:
            releaseName: cinder-csi
            valueFiles:
              - $values/helmfile/k8s-configs/cinder-csi/cinder-csi-values.yaml
        - repoURL: https://github.com/Kosenuel/Test-Infra
          targetRevision: main
          ref: values
      destination:
        server: '{{server}}'
        namespace: kube-system
      revisionHistoryLimit: 5
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: 5
          backoff:
            duration: 10s
            factor: 2
            maxDuration: 5m
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
          - PruneLast=true
          # I am disabling "ServerSideApply" for this ApplicationSet because the openstack-cinder-csi Helm chart's DaemonSet has a "deprecated.daemonset.template.generation" annotation that is updated by the kube-controller-manager and causes perpetual diffs. This is a known issue with the chart that has not been resolved for 2+ years, and I have no control over it since it's maintained by the OpenStack community. Disabling SSA allows Argo CD to ignore changes to this annotation and successfully sync the ApplicationSet without getting stuck in a loop.
          - ServerSideApply=false

  # ignoreDifferences:
  #   - group: apps
  #     kind: DaemonSet
  #     jqPathExpressions:
  #       - .metadata.annotations."deprecated.daemonset.template.generation"

