apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: platform-rancher-main
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - cluster: main
            server: https://kubernetes.default.svc
  template:
    metadata:
      name: 'platform-rancher-{{cluster}}'
      namespace: argocd
      finalizers:
        - resources-finalizer.argocd.argoproj.io
      annotations:
        argocd.argoproj.io/sync-wave: "30"
    spec:
      project: platform
      sources:
        - repoURL: https://releases.rancher.com/server-charts/latest
          chart: rancher
          targetRevision: 2.9.0
          helm:
            releaseName: rancher
            valueFiles:
              - $values/helmfile/values/rancher.yaml
        - repoURL: git@github.com:CMCC-Foundation/protocoast-infra.git
          targetRevision: main
          ref: values
      destination:
        server: '{{server}}'
        namespace: cattle-system
      revisionHistoryLimit: 5
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: 5
          backoff:
            duration: 10s
            factor: 2
            maxDuration: 5m
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
          - PruneLast=true
          - ServerSideApply=true
